services:
  - type: web
    name: aqi-dashboard
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
